name: Node.js CI

on:
  push:
    branches: [main, feat/*]
    tags:        
      - 'v*.*.*'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
      - name: Build tarballs
        if: startsWith(github.ref, 'refs/tags/')
        run: yarn build:standalone
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/**/*.tar.gz
          draft: true
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/')
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
